FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
RUN npm i

COPY lib ./lib
COPY cron.js ./

RUN node_modules/.bin/esbuild cron.js \
    --bundle \
    --platform=node \
    --packages=external \
    --format=esm \
    --outfile=cron.bundle.mjs

CMD ["node", "cron.bundle.mjs"]
